name: 'Create NuGet Package for Octopus Deploy'
description: 'GitHub Action to create a NuGet package for Octopus Deploy'
author: 'Octopus Deploy'
branding:
  color: 'blue'
  icon: 'package'

inputs:
  package_id:
    description: 'Package Id.'
    required: true
  version:
    description: 'Package version.'
    required: true
  output_folder:
    description: 'The folder to put the resulting package in, relative to the current working directory; not the base path.'
    required: true
  base_path:
    description: 'The base path for the input files.'
    required: true
  files:
    description: 'Multi-line list of files to include in the package. Supports globbing.'
    required: true
  nuspec_description:
    description: 'Description to include in the Nuspec file. '
    required: true
  nuspec_authors:
    description: 'Multi-line list of authors to include in the Nuspec file.'
    required: true
  nuspec_release_notes:
    description: 'Release notes to include in the Nuspec file.'

outputs:
  package_file_path:
    description: 'The full path to the package file that was created.'
  package_filename:
    description: 'The filename, without the path, of the file that was created.'

runs:
  using: 'node16'
  main: 'dist/index.js'
