name: 'build-test'
on:
  push:
    paths-ignore:
      - '**/*.md'

  schedule:
    # Daily 5am australian/brisbane time (7pm UTC)
    - cron: '0 19 * * *'
  workflow_dispatch:

# temp
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
    steps:
      - uses: actions/checkout@v3

      - name: Install package dependencies
        run: npm install

      - name: Compile and run tests
        run: npm run all

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JEST Tests
          path: 'reports/jest-*.xml'
          reporter: jest-junit

      - name: GitHub Action self-test
        id: self_test
        uses: ./
        with:
          package_id: 'TestNuGetPackage'
          version: '2.1.1'
          output_folder: './packaging'
          base_path: reports
          files: |
            **/*
          nuspec_description: 'self-test description'
          nuspec_authors: |
            author 1
            author 2
          nuspec_release_notes: |
            this is a multi-line
            release note

      - uses: actions/upload-artifact@v3
        with:
          name: TestNuGetPackage.2.1.1
          path: ${{ steps.self_test.outputs.package_file_path }}
